import { Check, ChevronRight, FileText, MapPin, MessageCircle, Plus, Send, SlidersHorizontal, Vote } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { useNavigate, useOutletContext, type NavigateFunction } from 'react-router-dom'
import { Button } from '../../components/Button'
import { EmptyState } from '../../components/EmptyState'
import { Sheet } from '../../components/Sheet'
import { useApp } from '../../context/AppContext'
import { dayLabel, initials, tripDayCount, uid } from '../../lib/utils'
import type { ChatMessage, ItineraryPlace, Proposal, Trip } from '../../types'

type Filter = 'all' | 'proposals' | 'decisions'
export function ChatScreen() {
  const { trip } = useOutletContext<{ trip: Trip }>(); const navigate = useNavigate(); const { data, profile, sendMessage, createProposal, vote, setProposalStatus, addPlace } = useApp()
  const [text, setText] = useState(''); const [filter, setFilter] = useState<Filter>('all'); const [proposalOpen, setProposalOpen] = useState(false); const [scheduleProposal, setScheduleProposal] = useState<Proposal | null>(null); const bottomRef = useRef<HTMLDivElement>(null)
  const messages = useMemo(() => data.messages.filter((message) => message.tripId === trip.id).filter((message) => filter === 'all' || filter === 'proposals' ? (filter === 'all' || message.type === 'PROPOSAL') : message.type === 'DECISION' || message.type === 'SYSTEM'), [data.messages, trip.id, filter])
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages.length])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!text.trim()) return; const body = text.trim(); try { await sendMessage(trip.id, body); setText('') } catch { return } }
  const addApprovedPlace = async (proposal: Proposal, day: number, startTime: string) => { const raw = proposal.proposedPlace || {}; try { const place = await addPlace({ tripId: trip.id, day, name: raw.name || proposal.title, address: raw.address || '', latitude: raw.latitude || 43.6532, longitude: raw.longitude || -79.3832, startTime, notes: raw.notes }); await setProposalStatus(proposal.id, 'APPROVED'); await sendMessage(trip.id, `${place.name}이(가) Day ${day + 1} 일정에 추가됐어요.`, 'SYSTEM', { referencedPlaceId: place.id }); setScheduleProposal(null) } catch { return } }
  return <section className="chat-screen"><div className="chat-filters"><button className={filter === 'all' ? 'is-active' : ''} onClick={() => setFilter('all')}>전체</button><button className={filter === 'proposals' ? 'is-active' : ''} onClick={() => setFilter('proposals')}>제안</button><button className={filter === 'decisions' ? 'is-active' : ''} onClick={() => setFilter('decisions')}>결정</button><button className="filter-icon" aria-label="필터"><SlidersHorizontal size={15} /></button></div><div className="message-scroll">{messages.length === 0 ? <EmptyState icon={MessageCircle} title={filter === 'all' ? '아직 메시지가 없어요' : '표시할 내용이 없어요'} description={filter === 'all' ? '이 여행에 대한 이야기를 시작해보세요.' : '새로운 제안과 결정을 기다리고 있어요.'} /> : messages.map((message) => <MessageItem key={message.id} message={message} mine={message.author.id === profile.id} proposal={data.proposals.find((proposal) => proposal.id === message.proposalId)} noteTitle={data.notes.find((note) => note.id === message.referencedNotePageId)?.title} place={data.places.find((place) => place.id === message.referencedPlaceId)} onNavigate={navigate} onVote={vote} onApprove={setScheduleProposal} />)}<div ref={bottomRef} /></div><form className="message-composer" onSubmit={submit}><button type="button" onClick={() => setProposalOpen(true)} aria-label="제안 만들기"><Plus size={21} /></button><input value={text} onChange={(event) => setText(event.target.value)} placeholder="메시지..." /><button type="submit" disabled={!text.trim()} aria-label="전송"><Send size={19} /></button></form>
    <NewProposalSheet tripId={trip.id} open={proposalOpen} onClose={() => setProposalOpen(false)} onCreate={async (title, description, options) => { await createProposal({ tripId: trip.id, title, description, options: options.map((label) => ({ id: uid(), label, voterIds: [] })), proposedPlace: { name: title } }); setProposalOpen(false) }} />
    <ScheduleSheet proposal={scheduleProposal} trip={trip} onClose={() => setScheduleProposal(null)} onAdd={addApprovedPlace} />
  </section>
}

function MessageItem({ message, mine, proposal, noteTitle, place, onNavigate, onVote, onApprove }: { message: ChatMessage; mine: boolean; proposal?: Proposal; noteTitle?: string; place?: ItineraryPlace; onNavigate: NavigateFunction; onVote: (proposalId: string, optionId: string) => Promise<void>; onApprove: (proposal: Proposal) => void }) {
  if (message.type === 'SYSTEM' || message.type === 'DECISION') return <div className="system-message"><Check size={14} />{message.body}</div>
  return <div className={`message-row ${mine ? 'is-mine' : ''}`}><span className="avatar avatar--small">{initials(message.author.name)}</span><div className="message-stack"><span className="message-author">{message.author.name}</span>{message.type === 'TEXT' && <div className="bubble">{message.body}</div>}{message.type === 'NOTE_SHARE' && <button className="shared-card" onClick={() => onNavigate(message.referencedNotePageId ? `../note/${message.referencedNotePageId}` : '../note')}><span><FileText size={18} /></span><div><small>노트를 공유했어요</small><strong>{noteTitle || message.body}</strong></div><ChevronRight size={18} /></button>}{message.type === 'PLACE_SHARE' && <button className="shared-card" onClick={() => onNavigate('../map', { state: { focusedId: place?.id } } as never)}><span><MapPin size={18} /></span><div><small>장소를 공유했어요</small><strong>{place?.name || message.body}</strong><em>{place?.address}</em></div><ChevronRight size={18} /></button>}{proposal && <ProposalCard proposal={proposal} onVote={onVote} onApprove={onApprove} />}</div></div>
}

function ProposalCard({ proposal, onVote, onApprove }: { proposal: Proposal; onVote: (proposalId: string, optionId: string) => Promise<void>; onApprove: (proposal: Proposal) => void }) {
  const totalVotes = proposal.options.reduce((sum, option) => sum + option.voterIds.length, 0)
  return <article className="proposal-card"><div className="proposal-card__head"><span><Vote size={15} /> 제안</span><em className={`status status--${proposal.status.toLowerCase()}`}>{proposal.status}</em></div><h3>{proposal.title}</h3>{proposal.description && <p>{proposal.description}</p>}<div className="poll-options">{proposal.options.map((option) => { const count = option.voterIds.length; return <button disabled={proposal.status !== 'OPEN'} key={option.id} onClick={() => { void onVote(proposal.id, option.id).catch(() => {}) }}><span style={{ width: totalVotes ? `${Math.max(4, count / totalVotes * 100)}%` : '0%' }} /><strong>{option.label}</strong><em>{count}</em></button> })}</div>{proposal.status === 'OPEN' && proposal.proposedPlace && <Button full onClick={() => onApprove(proposal)}>승인하고 일정에 추가</Button>}</article>
}

function NewProposalSheet({ tripId, open, onClose, onCreate }: { tripId: string; open: boolean; onClose: () => void; onCreate: (title: string, description: string, options: string[]) => Promise<void> }) {
  void tripId
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [options, setOptions] = useState(['좋아요', '건너뛰기', '상관없어요'])
  return <Sheet open={open} title="새 제안" onClose={onClose} tall><form className="sheet-form" onSubmit={(event) => { event.preventDefault(); void onCreate(title.trim(), description.trim(), options.filter(Boolean)).catch(() => {}) }}><label className="field"><span>제안 제목</span><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="예: 토론토 아일랜드 가기" /></label><label className="field"><span>한마디 · 선택</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="왜 가고 싶은지 알려주세요" /></label><div className="field"><span>투표 선택지</span>{options.map((option, index) => <input key={index} required value={option} onChange={(event) => setOptions(options.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} />)}<button type="button" className="inline-add" onClick={() => setOptions([...options, ''])}><Plus size={15} /> 선택지 추가</button></div><Button full type="submit">채팅에 보내기</Button></form></Sheet>
}

function ScheduleSheet({ proposal, trip, onClose, onAdd }: { proposal: Proposal | null; trip: Trip; onClose: () => void; onAdd: (proposal: Proposal, day: number, time: string) => void }) {
  const [day, setDay] = useState(0); const [time, setTime] = useState('')
  if (!proposal) return null
  return <Sheet open title="일정에 추가" onClose={onClose}><div className="schedule-summary"><MapPin size={20} /><strong>{proposal.title}</strong></div><label className="field"><span>여행 날짜</span><select value={day} onChange={(event) => setDay(Number(event.target.value))}>{Array.from({ length: tripDayCount(trip.startDate, trip.endDate) }, (_, index) => <option key={index} value={index}>{dayLabel(trip.startDate, index)}</option>)}</select></label><label className="field"><span>시간 · 선택</span><input type="time" value={time} onChange={(event) => setTime(event.target.value)} /></label><Button full onClick={() => onAdd(proposal, day, time)}>일정에 추가</Button></Sheet>
}
