import { ChevronLeft, Copy, FileText, GripVertical, MapPin, MoreHorizontal, Plus, Send, Trash2, Vote } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useOutletContext, useParams } from 'react-router-dom'
import { Button } from '../../components/Button'
import { EmptyState } from '../../components/EmptyState'
import { Sheet } from '../../components/Sheet'
import { useApp } from '../../context/AppContext'
import { uid } from '../../lib/utils'
import type { BlockType, NoteBlock, NotePage, Trip } from '../../types'

const blockOptions: Array<{ type: BlockType; label: string; hint: string }> = [
  { type: 'paragraph', label: '텍스트', hint: '자유롭게 입력' }, { type: 'heading1', label: '제목 1', hint: '큰 섹션 제목' },
  { type: 'heading2', label: '제목 2', hint: '중간 섹션 제목' }, { type: 'bullet', label: '글머리 목록', hint: '아이디어 정리' },
  { type: 'numbered', label: '번호 목록', hint: '순서가 있는 항목' }, { type: 'todo', label: '할 일', hint: '체크 가능한 항목' },
  { type: 'toggle', label: '토글', hint: '접을 수 있는 정보' }, { type: 'quote', label: '콜아웃', hint: '중요한 메모' },
  { type: 'divider', label: '구분선', hint: '내용 나누기' }, { type: 'link', label: '링크', hint: '웹 주소' }, { type: 'location', label: '장소', hint: '지도에 추가할 후보' }
]

export function NoteScreen() {
  const { trip } = useOutletContext<{ trip: Trip }>(); const { pageId } = useParams(); const navigate = useNavigate()
  const { data, addNotePage, updateNotePage, deleteNotePage, duplicateNotePage, sendMessage, createProposal } = useApp()
  const pages = useMemo(() => data.notes.filter((page) => page.tripId === trip.id), [data.notes, trip.id])
  const activePage = pages.find((page) => page.id === pageId)
  const [menuPage, setMenuPage] = useState<NotePage | null>(null); const [blockMenu, setBlockMenu] = useState(false); const [actionBlock, setActionBlock] = useState<NoteBlock | null>(null)
  useEffect(() => { if (pageId && !activePage) navigate(`/trip/${trip.id}/note`, { replace: true }) }, [pageId, activePage, navigate, trip.id])
  const createPage = async () => { try { const page = await addNotePage(trip.id); navigate(`/trip/${trip.id}/note/${page.id}`) } catch { return } }
  if (!activePage) return <section className="note-home"><div className="tab-heading"><span>NOTE</span><h2>여행 노트</h2><p>아이디어와 정보를 자유롭게 모아두세요.</p></div>{pages.length === 0 ? <EmptyState icon={FileText} title="아직 페이지가 없어요" description="첫 페이지를 만들고 여행 이야기를 시작해보세요." action={<Button onClick={createPage}><Plus size={17} /> 첫 페이지 만들기</Button>} /> : <div className="page-list">{pages.map((page) => <button key={page.id} onClick={() => navigate(`/trip/${trip.id}/note/${page.id}`)} className="page-row"><FileText size={19} /><span><strong>{page.title}</strong><small>{page.blocks.filter((block) => block.content).length}개 블록</small></span><button className="icon-button" onClick={(event) => { event.stopPropagation(); setMenuPage(page) }}><MoreHorizontal size={20} /></button></button>)}</div>}<button className="new-page-button" onClick={createPage}><Plus size={18} /> 새 페이지</button>
    <Sheet open={Boolean(menuPage)} title="페이지 옵션" onClose={() => setMenuPage(null)}>{menuPage && <div className="action-list"><button onClick={() => { void duplicateNotePage(menuPage.id).catch(() => {}); setMenuPage(null) }}><Copy size={18} /> 복제</button><button onClick={() => { void sendMessage(trip.id, menuPage.title, 'NOTE_SHARE', { referencedNotePageId: menuPage.id }).catch(() => {}); setMenuPage(null) }}><Send size={18} /> 채팅에 공유</button><button onClick={() => { void createProposal({ tripId: trip.id, title: menuPage.title, description: '이 아이디어를 여행 계획에 반영할까요?', referencedNotePageId: menuPage.id, options: [{ id: uid(), label: '좋아요', voterIds: [] }, { id: uid(), label: '건너뛰기', voterIds: [] }, { id: uid(), label: '상관없어요', voterIds: [] }] }).catch(() => {}); setMenuPage(null) }}><Vote size={18} /> 제안하기</button><button className="danger" onClick={() => { void deleteNotePage(menuPage.id).catch(() => {}); setMenuPage(null) }}><Trash2 size={18} /> 삭제</button></div>}</Sheet></section>

  const updateBlock = (id: string, changes: Partial<NoteBlock>) => updateNotePage(activePage.id, { blocks: activePage.blocks.map((block) => block.id === id ? { ...block, ...changes } : block) })
  const addBlock = (type: BlockType) => { updateNotePage(activePage.id, { blocks: [...activePage.blocks, { id: uid(), type, content: '' }] }); setBlockMenu(false) }
  return <section className="note-editor"><div className="editor-topbar"><button className="icon-button" onClick={() => navigate(`/trip/${trip.id}/note`)}><ChevronLeft size={22} /></button><span>NOTE</span><button className="icon-button" onClick={() => setMenuPage(activePage)}><MoreHorizontal size={21} /></button></div><input className="page-title-input" aria-label="페이지 제목" value={activePage.title} onChange={(event) => updateNotePage(activePage.id, { title: event.target.value })} placeholder="제목 없음" /><div className="block-list">{activePage.blocks.map((block, index) => <BlockEditor key={block.id} block={block} index={index} onChange={(changes) => updateBlock(block.id, changes)} onAction={() => setActionBlock(block)} />)}</div><button className="add-block-button" onClick={() => setBlockMenu(true)}><Plus size={17} /> 블록 추가</button>
    <Sheet open={blockMenu} title="블록 추가" onClose={() => setBlockMenu(false)} tall><div className="block-picker">{blockOptions.map((option) => <button key={option.type} onClick={() => addBlock(option.type)}><span>{option.type === 'location' ? <MapPin size={18} /> : option.label.slice(0, 1)}</span><div><strong>{option.label}</strong><small>{option.hint}</small></div></button>)}</div></Sheet>
    <Sheet open={Boolean(actionBlock)} title="블록 옵션" onClose={() => setActionBlock(null)}>{actionBlock && <div className="action-list"><button onClick={() => { void sendMessage(trip.id, actionBlock.content, 'NOTE_SHARE', { referencedNotePageId: activePage.id }).catch(() => {}); setActionBlock(null) }}><Send size={18} /> 채팅에 공유</button><button onClick={() => { void createProposal({ tripId: trip.id, title: actionBlock.content || activePage.title, description: '이 아이디어를 여행 계획에 반영할까요?', referencedNotePageId: activePage.id, proposedPlace: actionBlock.type === 'location' ? { name: actionBlock.content } : undefined, options: [{ id: uid(), label: '좋아요', voterIds: [] }, { id: uid(), label: '건너뛰기', voterIds: [] }, { id: uid(), label: '상관없어요', voterIds: [] }] }).catch(() => {}); setActionBlock(null) }}><Vote size={18} /> 제안하기</button>{actionBlock.type === 'location' && <button onClick={() => navigate(`/trip/${trip.id}/map`, { state: { placeName: actionBlock.content } })}><MapPin size={18} /> 지도에 추가</button>}<button className="danger" onClick={() => { updateNotePage(activePage.id, { blocks: activePage.blocks.filter((block) => block.id !== actionBlock.id) }); setActionBlock(null) }}><Trash2 size={18} /> 삭제</button></div>}</Sheet>
    <Sheet open={Boolean(menuPage)} title="페이지 옵션" onClose={() => setMenuPage(null)}>{menuPage && <div className="action-list"><button onClick={() => { void sendMessage(trip.id, activePage.title, 'NOTE_SHARE', { referencedNotePageId: activePage.id }).catch(() => {}); setMenuPage(null) }}><Send size={18} /> 채팅에 공유</button><button onClick={() => { void duplicateNotePage(activePage.id).catch(() => {}); setMenuPage(null) }}><Copy size={18} /> 복제</button><button className="danger" onClick={() => { void deleteNotePage(activePage.id).then(() => navigate(`/trip/${trip.id}/note`)).catch(() => {}) }}><Trash2 size={18} /> 삭제</button></div>}</Sheet>
  </section>
}

function BlockEditor({ block, index, onChange, onAction }: { block: NoteBlock; index: number; onChange: (changes: Partial<NoteBlock>) => void; onAction: () => void }) {
  if (block.type === 'divider') return <div className="editable-block divider-block"><hr /><button onClick={onAction}><MoreHorizontal size={17} /></button></div>
  const prefix = block.type === 'bullet' ? '•' : block.type === 'numbered' ? `${index + 1}.` : block.type === 'toggle' ? '›' : null
  return <div className={`editable-block block--${block.type}`}><button className="block-grip" onClick={onAction} aria-label="블록 옵션"><GripVertical size={16} /></button>{block.type === 'todo' && <input type="checkbox" checked={Boolean(block.checked)} onChange={(event) => onChange({ checked: event.target.checked })} />}{prefix && <span className="block-prefix">{prefix}</span>}<textarea rows={1} value={block.content} placeholder={block.type === 'location' ? '장소 이름 입력' : '내용 입력'} onChange={(event) => { onChange({ content: event.target.value }); event.target.style.height = 'auto'; event.target.style.height = `${event.target.scrollHeight}px` }} />{block.type === 'location' && <MapPin size={17} />}</div>
}
