import { ChevronLeft, Copy, FileText, MapPin, MoreHorizontal, Plus, Send, Trash2, Vote } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useOutletContext, useParams } from 'react-router-dom'
import { Button } from '../../components/Button'
import { EmptyState } from '../../components/EmptyState'
import { Sheet } from '../../components/Sheet'
import { useApp } from '../../context/AppContext'
import { uid } from '../../lib/utils'
import type { NoteBlock, NotePage, Trip } from '../../types'
import { NoteEditor } from './NoteEditor'

export function NoteScreen() {
  const { trip } = useOutletContext<{ trip: Trip }>(); const { pageId } = useParams(); const navigate = useNavigate()
  const { data, addNotePage, updateNotePage, deleteNotePage, duplicateNotePage, sendMessage, createProposal } = useApp()
  const pages = useMemo(() => data.notes.filter((page) => page.tripId === trip.id), [data.notes, trip.id])
  const activePage = pages.find((page) => page.id === pageId)
  const [menuPage, setMenuPage] = useState<NotePage | null>(null); const [actionTarget, setActionTarget] = useState<{ block: NoteBlock; remove: () => void } | null>(null)
  useEffect(() => { if (pageId && !activePage) navigate(`/trip/${trip.id}/note`, { replace: true }) }, [pageId, activePage, navigate, trip.id])
  const createPage = async () => { try { const page = await addNotePage(trip.id); navigate(`/trip/${trip.id}/note/${page.id}`) } catch { return } }
  if (!activePage) return <section className="note-home"><div className="tab-heading"><span>NOTE</span><h2>여행 노트</h2><p>아이디어와 정보를 자유롭게 모아두세요.</p></div>{pages.length === 0 ? <EmptyState icon={FileText} title="아직 페이지가 없어요" description="첫 페이지를 만들고 여행 이야기를 시작해보세요." action={<Button onClick={createPage}><Plus size={17} /> 첫 페이지 만들기</Button>} /> : <div className="page-list">{pages.map((page) => <button key={page.id} onClick={() => navigate(`/trip/${trip.id}/note/${page.id}`)} className="page-row"><FileText size={19} /><span><strong>{page.title}</strong><small>{page.blocks.filter((block) => block.content).length}개 블록</small></span><button className="icon-button" onClick={(event) => { event.stopPropagation(); setMenuPage(page) }}><MoreHorizontal size={20} /></button></button>)}</div>}<button className="new-page-button" onClick={createPage}><Plus size={18} /> 새 페이지</button>
    <Sheet open={Boolean(menuPage)} title="페이지 옵션" onClose={() => setMenuPage(null)}>{menuPage && <div className="action-list"><button onClick={() => { void duplicateNotePage(menuPage.id).catch(() => {}); setMenuPage(null) }}><Copy size={18} /> 복제</button><button onClick={() => { void sendMessage(trip.id, menuPage.title, 'NOTE_SHARE', { referencedNotePageId: menuPage.id }).catch(() => {}); setMenuPage(null) }}><Send size={18} /> 채팅에 공유</button><button onClick={() => { void createProposal({ tripId: trip.id, title: menuPage.title, description: '이 아이디어를 여행 계획에 반영할까요?', referencedNotePageId: menuPage.id, options: [{ id: uid(), label: '좋아요', voterIds: [] }, { id: uid(), label: '건너뛰기', voterIds: [] }, { id: uid(), label: '상관없어요', voterIds: [] }] }).catch(() => {}); setMenuPage(null) }}><Vote size={18} /> 제안하기</button><button className="danger" onClick={() => { void deleteNotePage(menuPage.id).catch(() => {}); setMenuPage(null) }}><Trash2 size={18} /> 삭제</button></div>}</Sheet></section>

  return <section className="note-editor"><div className="editor-topbar"><button className="icon-button" onClick={() => navigate(`/trip/${trip.id}/note`)}><ChevronLeft size={22} /></button><span>NOTE</span><button className="icon-button" onClick={() => setMenuPage(activePage)}><MoreHorizontal size={21} /></button></div><input className="page-title-input" aria-label="페이지 제목" value={activePage.title} onChange={(event) => updateNotePage(activePage.id, { title: event.target.value })} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); document.querySelector<HTMLTextAreaElement>('.editor-blocks textarea')?.focus() } }} placeholder="제목 없음" /><NoteEditor pageId={activePage.id} blocks={activePage.blocks} onBlocksChange={(blocks) => updateNotePage(activePage.id, { blocks })} onAction={setActionTarget} />
    <Sheet open={Boolean(actionTarget)} title="블록 옵션" onClose={() => setActionTarget(null)}>{actionTarget && <div className="action-list"><button onClick={() => { void sendMessage(trip.id, actionTarget.block.content, 'NOTE_SHARE', { referencedNotePageId: activePage.id }).catch(() => {}); setActionTarget(null) }}><Send size={18} /> 채팅에 공유</button><button onClick={() => { void createProposal({ tripId: trip.id, title: actionTarget.block.content || activePage.title, description: '이 아이디어를 여행 계획에 반영할까요?', referencedNotePageId: activePage.id, proposedPlace: actionTarget.block.type === 'location' ? { name: actionTarget.block.content } : undefined, options: [{ id: uid(), label: '좋아요', voterIds: [] }, { id: uid(), label: '건너뛰기', voterIds: [] }, { id: uid(), label: '상관없어요', voterIds: [] }] }).catch(() => {}); setActionTarget(null) }}><Vote size={18} /> 제안하기</button>{actionTarget.block.type === 'location' && <button onClick={() => navigate(`/trip/${trip.id}/map`, { state: { placeName: actionTarget.block.content } })}><MapPin size={18} /> 지도에 추가</button>}<button className="danger" onClick={() => { actionTarget.remove(); setActionTarget(null) }}><Trash2 size={18} /> 삭제</button></div>}</Sheet>
    <Sheet open={Boolean(menuPage)} title="페이지 옵션" onClose={() => setMenuPage(null)}>{menuPage && <div className="action-list"><button onClick={() => { void sendMessage(trip.id, activePage.title, 'NOTE_SHARE', { referencedNotePageId: activePage.id }).catch(() => {}); setMenuPage(null) }}><Send size={18} /> 채팅에 공유</button><button onClick={() => { void duplicateNotePage(activePage.id).catch(() => {}); setMenuPage(null) }}><Copy size={18} /> 복제</button><button className="danger" onClick={() => { void deleteNotePage(activePage.id).then(() => navigate(`/trip/${trip.id}/note`)).catch(() => {}) }}><Trash2 size={18} /> 삭제</button></div>}</Sheet>
  </section>
}
