import { DndContext, PointerSensor, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { Bike, Car, ChevronRight, Footprints, GripVertical, MapPin } from 'lucide-react'
import type { ItineraryPlace, TransportSegment } from '../../types'
import { timeLabel } from '../../lib/utils'

export function ItineraryList({ places, segments, onReorder, onSelect, onSegment }: { places: ItineraryPlace[]; segments: TransportSegment[]; onReorder: (ids: string[]) => void; onSelect: (place: ItineraryPlace) => void; onSegment: (from: ItineraryPlace, to: ItineraryPlace, segment?: TransportSegment) => void }) {
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }))
  const dragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const ids = places.map((place) => place.id); const from = ids.indexOf(String(active.id)); const to = ids.indexOf(String(over.id)); ids.splice(to, 0, ids.splice(from, 1)[0]); onReorder(ids) }
  return <div className="itinerary-list"><DndContext sensors={sensors} onDragEnd={dragEnd}><SortableContext items={places.map((place) => place.id)} strategy={verticalListSortingStrategy}>{places.map((place, index) => { const next = places[index + 1]; const segment = next ? segments.find((item) => item.sourcePlaceId === place.id && item.destinationPlaceId === next.id) : undefined; return <div key={place.id}><SortablePlace place={place} order={index + 1} onSelect={onSelect} />{next && <button className="transport-row" onClick={() => onSegment(place, next, segment)}>{segment?.mode === 'driving' ? <Car size={17} /> : segment?.mode === 'cycling' ? <Bike size={17} /> : <Footprints size={17} />}<span>{segment?.duration ? `${segment.duration}분` : '이동 정보 추가'}{segment?.distance ? ` · ${segment.distance}km` : ''}</span><ChevronRight size={16} /></button>}</div> })}</SortableContext></DndContext></div>
}
function SortablePlace({ place, order, onSelect }: { place: ItineraryPlace; order: number; onSelect: (place: ItineraryPlace) => void }) { const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: place.id }); return <article ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }} className="itinerary-card"><button className="drag-handle" {...attributes} {...listeners}><GripVertical size={18} /></button><button className="itinerary-card__content" onClick={() => onSelect(place)}><span className="order-dot">{order}</span><div><time>{timeLabel(place.startTime)}</time><h3>{place.name}</h3><p><MapPin size={13} />{place.address || '주소 없음'}</p></div><ChevronRight size={18} /></button></article> }
