import { DndContext, PointerSensor, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { ChevronRight, Footprints, GripVertical, MapPin } from 'lucide-react'
import type { ItineraryPlace, TransportSegment } from '../../types'
import { timeRangeLabel } from '../../lib/utils'
import { transportModeOption } from './transportModes'

export function ItineraryList({ places, segments, onReorder, onSelect, onSegment }: { places: ItineraryPlace[]; segments: TransportSegment[]; onReorder: (ids: string[]) => void; onSelect: (place: ItineraryPlace) => void; onSegment: (from: ItineraryPlace, to: ItineraryPlace, segment?: TransportSegment) => void }) {
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }))
  const dragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const ids = places.map((place) => place.id); const from = ids.indexOf(String(active.id)); const to = ids.indexOf(String(over.id)); ids.splice(to, 0, ids.splice(from, 1)[0]); onReorder(ids) }
  return <div className="itinerary-list"><DndContext sensors={sensors} onDragEnd={dragEnd}><SortableContext items={places.map((place) => place.id)} strategy={verticalListSortingStrategy}>{places.map((place, index) => { const next = places[index + 1]; const segment = next ? segments.find((item) => item.sourcePlaceId === place.id && item.destinationPlaceId === next.id) : undefined; const ModeIcon = segment ? transportModeOption(segment.mode).Icon : Footprints; return <div key={place.id}><SortablePlace place={place} order={index + 1} onSelect={onSelect} />{next && <button className={`transport-row ${segment ? 'has-transport' : ''}`} onClick={() => onSegment(place, next, segment)} aria-label={segment ? `이동 정보 수정 · ${segment.duration ? `${segment.duration}분` : '시간 미정'}` : '이동 정보 추가'}><ModeIcon size={segment ? 18 : 17} aria-hidden="true" /><span>{segment ? segment.duration ? `${segment.duration}분` : '시간 미정' : '이동 정보 추가'}</span></button>}</div> })}</SortableContext></DndContext></div>
}
function SortablePlace({ place, order, onSelect }: { place: ItineraryPlace; order: number; onSelect: (place: ItineraryPlace) => void }) { const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: place.id }); return <article ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }} className="itinerary-card"><button className="drag-handle" {...attributes} {...listeners}><GripVertical size={18} /></button><button className="itinerary-card__content" onClick={() => onSelect(place)}><span className="order-dot">{order}</span><div><time>{timeRangeLabel(place.startTime, place.endTime)}</time><h3>{place.name}</h3><p><MapPin size={13} /><span>{place.address || '주소 없음'}</span></p></div><ChevronRight size={18} /></button></article> }
