import { ChevronLeft, ChevronRight, ExternalLink, List, Map as MapIcon, MapPin, Navigation, Plus, Search, Send, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { useLocation, useOutletContext } from 'react-router-dom'
import { Button } from '../../components/Button'
import { EmptyState } from '../../components/EmptyState'
import { Sheet } from '../../components/Sheet'
import { useApp } from '../../context/AppContext'
import { searchPlaces, type PlaceSearchResult } from '../../lib/mapbox'
import { dayLabel, googleMapsUrl, tripDayCount, uid } from '../../lib/utils'
import type { ItineraryPlace, TransportMode, TransportSegment, Trip } from '../../types'
import { ItineraryList } from './ItineraryList'
import { MapCanvas } from './MapCanvas'

export function MapScreen() {
  const { trip } = useOutletContext<{ trip: Trip }>(); const location = useLocation(); const { data, addPlace, deletePlace, reorderPlaces, upsertSegment, sendMessage } = useApp()
  const savedDay = Number(localStorage.getItem(`tlog:day:${trip.id}`) || 0); const savedView = (localStorage.getItem(`tlog:view:${trip.id}`) || 'map') as 'map' | 'list'
  const [day, setDayState] = useState(Math.min(savedDay, tripDayCount(trip.startDate, trip.endDate) - 1)); const [view, setViewState] = useState<'map' | 'list'>(savedView); const [addOpen, setAddOpen] = useState(false); const [selected, setSelected] = useState<ItineraryPlace | null>(null); const [segmentPair, setSegmentPair] = useState<{ from: ItineraryPlace; to: ItineraryPlace; segment?: TransportSegment } | null>(null)
  const places = useMemo(() => data.places.filter((place) => place.tripId === trip.id && place.day === day).sort((a, b) => a.sortOrder - b.sortOrder), [data.places, trip.id, day]); const segments = data.segments.filter((segment) => segment.tripId === trip.id && segment.day === day)
  const setDay = (next: number) => { setDayState(next); localStorage.setItem(`tlog:day:${trip.id}`, String(next)) }; const setView = (next: 'map' | 'list') => { setViewState(next); localStorage.setItem(`tlog:view:${trip.id}`, next) }
  useEffect(() => { const state = location.state as { placeName?: string } | null; if (state?.placeName) setAddOpen(true) }, [location.state])
  const addNewPlace = (result: PlaceSearchResult, details: { startTime: string; notes: string }) => { addPlace({ tripId: trip.id, day, name: result.name, address: result.address, latitude: result.latitude, longitude: result.longitude, startTime: details.startTime, notes: details.notes, providerPlaceId: result.id }); setAddOpen(false) }
  return <section className="map-screen"><div className="map-controls"><div className="day-switcher"><button disabled={day === 0} onClick={() => setDay(day - 1)}><ChevronLeft size={20} /></button><strong>{dayLabel(trip.startDate, day)}</strong><button disabled={day === tripDayCount(trip.startDate, trip.endDate) - 1} onClick={() => setDay(day + 1)}><ChevronRight size={20} /></button></div><div className="view-toggle"><button className={view === 'map' ? 'is-active' : ''} onClick={() => setView('map')}><MapIcon size={15} /> MAP</button><button className={view === 'list' ? 'is-active' : ''} onClick={() => setView('list')}><List size={15} /> LIST</button></div></div>
    {view === 'map' ? <div className="map-stage"><MapCanvas places={places} focusedId={selected?.id} onSelect={setSelected} />{places.length === 0 && <div className="map-empty"><span>Day {day + 1}에 아직 일정이 없어요</span><button onClick={() => setAddOpen(true)}>첫 장소 추가</button></div>}<button className="map-fab" onClick={() => setAddOpen(true)}><Plus size={24} /></button></div> : <div className="list-stage">{places.length === 0 ? <EmptyState icon={MapPin} title={`Day ${day + 1} 일정이 비어 있어요`} description="장소를 추가하면 이동 순서와 교통 정보를 정리할 수 있어요." action={<Button onClick={() => setAddOpen(true)}><Plus size={17} /> 장소 추가</Button>} /> : <ItineraryList places={places} segments={segments} onReorder={(ids) => reorderPlaces(trip.id, day, ids)} onSelect={setSelected} onSegment={(from, to, segment) => setSegmentPair({ from, to, segment })} />}<button className="list-add" onClick={() => setAddOpen(true)}><Plus size={18} /> 장소 추가</button></div>}
    <AddPlaceSheet open={addOpen} initialQuery={(location.state as { placeName?: string } | null)?.placeName || ''} onClose={() => setAddOpen(false)} onAdd={addNewPlace} />
    <Sheet open={Boolean(selected)} title="장소 정보" onClose={() => setSelected(null)}>{selected && <div className="place-detail"><span className="place-detail__icon"><MapPin size={22} /></span><h3>{selected.name}</h3><p>{selected.address || '주소 없음'}</p>{selected.startTime && <time>{selected.startTime}</time>}{selected.notes && <div className="note-box">{selected.notes}</div>}<a className="button button--secondary button--full" href={googleMapsUrl(selected.name, selected.latitude, selected.longitude)} target="_blank" rel="noreferrer"><Navigation size={17} /> Google Maps에서 열기</a><Button full onClick={() => { sendMessage(trip.id, selected.name, 'PLACE_SHARE', { referencedPlaceId: selected.id }); setSelected(null) }}><Send size={17} /> 채팅에 공유</Button><button className="text-danger" onClick={() => { deletePlace(selected.id); setSelected(null) }}><Trash2 size={16} /> 장소 삭제</button></div>}</Sheet>
    <TransportSheet pair={segmentPair} tripId={trip.id} day={day} onClose={() => setSegmentPair(null)} onSave={(segment) => { upsertSegment(segment); setSegmentPair(null) }} />
  </section>
}

function AddPlaceSheet({ open, initialQuery, onClose, onAdd }: { open: boolean; initialQuery: string; onClose: () => void; onAdd: (result: PlaceSearchResult, details: { startTime: string; notes: string }) => void }) {
  const [query, setQuery] = useState(initialQuery); const [results, setResults] = useState<PlaceSearchResult[]>([]); const [selected, setSelected] = useState<PlaceSearchResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [startTime, setStartTime] = useState(''); const [notes, setNotes] = useState('')
  useEffect(() => { if (open) setQuery(initialQuery) }, [open, initialQuery])
  useEffect(() => { if (!open || query.trim().length < 2) { setResults([]); return }; const timer = setTimeout(async () => { setLoading(true); setError(''); try { const found = await searchPlaces(query); setResults(found); if (!found.length) setError('검색 결과가 없어요. Mapbox 설정도 확인해 주세요.') } catch { setError('장소를 검색하지 못했어요. 잠시 후 다시 시도해 주세요.') } finally { setLoading(false) } }, 350); return () => clearTimeout(timer) }, [query, open])
  const manualResult = (): PlaceSearchResult => ({ id: uid(), name: query.trim(), address: '', latitude: 43.6532, longitude: -79.3832 })
  return <Sheet open={open} title={selected ? '일정에 추가' : '장소 찾기'} onClose={onClose} tall>{selected ? <form className="sheet-form" onSubmit={(event) => { event.preventDefault(); onAdd(selected, { startTime, notes }) }}><div className="selected-place"><MapPin size={20} /><div><strong>{selected.name}</strong><span>{selected.address || '주소 없음'}</span></div></div><label className="field"><span>시작 시간 · 선택</span><input type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} /></label><label className="field"><span>메모 · 선택</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="예약, 티켓, 만날 장소..." /></label><Button full type="submit">추가</Button><Button full type="button" variant="ghost" onClick={() => setSelected(null)}>다시 검색</Button></form> : <><label className="search-field"><Search size={19} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="장소 검색..." />{loading && <span className="tiny-loader" />}</label><div className="search-results">{results.map((result) => <button key={result.id} onClick={() => setSelected(result)}><span><MapPin size={18} /></span><div><strong>{result.name}</strong><small>{result.address}</small></div><ChevronRight size={18} /></button>)}{query.trim().length >= 2 && !loading && <button className="manual-place" onClick={() => setSelected(manualResult())}><span><Plus size={18} /></span><div><strong>“{query.trim()}” 직접 추가</strong><small>나중에 정확한 위치를 수정할 수 있어요</small></div></button>}{error && <p className="inline-error">{error}</p>}</div></>}</Sheet>
}

function TransportSheet({ pair, tripId, day, onClose, onSave }: { pair: { from: ItineraryPlace; to: ItineraryPlace; segment?: TransportSegment } | null; tripId: string; day: number; onClose: () => void; onSave: (segment: TransportSegment) => void }) {
  const [mode, setMode] = useState<TransportMode>('walk'); const [duration, setDuration] = useState(''); const [distance, setDistance] = useState(''); const [notes, setNotes] = useState('')
  useEffect(() => { if (pair) { setMode(pair.segment?.mode || 'walk'); setDuration(pair.segment?.duration?.toString() || ''); setDistance(pair.segment?.distance?.toString() || ''); setNotes(pair.segment?.notes || '') } }, [pair])
  if (!pair) return null
  const modes: Array<[TransportMode, string]> = [['walk', '도보'], ['driving', '자동차'], ['transit', '대중교통'], ['cycling', '자전거'], ['ferry', '페리'], ['shuttle', '셔틀'], ['other', '기타']]
  return <Sheet open title="이동 정보" onClose={onClose}><form className="sheet-form" onSubmit={(event: FormEvent) => { event.preventDefault(); onSave({ id: pair.segment?.id || uid(), tripId, day, sourcePlaceId: pair.from.id, destinationPlaceId: pair.to.id, mode, duration: duration ? Number(duration) : undefined, distance: distance ? Number(distance) : undefined, notes }) }}><div className="route-summary"><span>{pair.from.name}</span><ExternalLink size={15} /><span>{pair.to.name}</span></div><div className="mode-picker">{modes.map(([value, label]) => <button type="button" className={mode === value ? 'is-active' : ''} key={value} onClick={() => setMode(value)}>{label}</button>)}</div><div className="field-grid"><label className="field"><span>소요 시간 · 분</span><input inputMode="numeric" value={duration} onChange={(event) => setDuration(event.target.value)} /></label><label className="field"><span>거리 · km</span><input inputMode="decimal" value={distance} onChange={(event) => setDistance(event.target.value)} /></label></div><label className="field"><span>메모</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><Button full type="submit">저장</Button></form></Sheet>
}
