import { ChevronLeft, ChevronRight, ExternalLink, Link as LinkIcon, List, Map as MapIcon, MapPin, MousePointer2, Navigation, Plus, Search, Send, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { useLocation, useNavigate, useOutletContext } from 'react-router-dom'
import { Button } from '../../components/Button'
import { EmptyState } from '../../components/EmptyState'
import { Sheet } from '../../components/Sheet'
import { useApp } from '../../context/AppContext'
import { googleMapsUrl, dayLabel, tripDayCount, uid } from '../../lib/utils'
import { reverseGeocode, searchPlaces, type PlaceSearchResult } from '../../services/geocoding'
import { googleMapsSearchFallbacks, parseOrResolveGoogleMapsUrl, type ParsedGoogleMapsPlace } from '../../services/googleMapsLink'
import type { ItineraryPlace, TransportMode, TransportSegment, Trip } from '../../types'
import { ItineraryList } from './ItineraryList'
import { MapCanvas } from './MapCanvas'

interface Coordinate { latitude: number; longitude: number }
type PlaceCandidate = Pick<ItineraryPlace, 'name' | 'address' | 'latitude' | 'longitude' | 'source' | 'googleMapsUrl' | 'providerPlaceId'>

export function MapScreen() {
  const { trip } = useOutletContext<{ trip: Trip }>(); const location = useLocation(); const navigate = useNavigate(); const { data, addPlace, deletePlace, reorderPlaces, upsertSegment, sendMessage } = useApp()
  const savedDay = Number(localStorage.getItem(`tlog:day:${trip.id}`) || 0); const savedView = (localStorage.getItem(`tlog:view:${trip.id}`) || 'map') as 'map' | 'list'
  const [day, setDayState] = useState(Math.min(savedDay, tripDayCount(trip.startDate, trip.endDate) - 1)); const [view, setViewState] = useState<'map' | 'list'>(savedView); const [addOpen, setAddOpen] = useState(false); const [selected, setSelected] = useState<ItineraryPlace | null>(null); const [segmentPair, setSegmentPair] = useState<{ from: ItineraryPlace; to: ItineraryPlace; segment?: TransportSegment } | null>(null); const [pinMode, setPinMode] = useState(false); const [draftPin, setDraftPin] = useState<Coordinate | null>(null)
  const places = useMemo(() => data.places.filter((place) => place.tripId === trip.id && place.day === day).sort((a, b) => a.sortOrder - b.sortOrder), [data.places, trip.id, day]); const segments = data.segments.filter((segment) => segment.tripId === trip.id && segment.day === day)
  const setDay = (next: number) => { setDayState(next); localStorage.setItem(`tlog:day:${trip.id}`, String(next)) }; const setView = (next: 'map' | 'list') => { setViewState(next); localStorage.setItem(`tlog:view:${trip.id}`, next) }
  useEffect(() => { const state = location.state as { placeName?: string; focusedId?: string } | null; let consumed = false; if (state?.placeName) { setAddOpen(true); consumed = true } if (state?.focusedId) { const place = data.places.find((item) => item.id === state.focusedId); if (place) { setDayState(place.day); localStorage.setItem(`tlog:day:${trip.id}`, String(place.day)); setViewState('map'); localStorage.setItem(`tlog:view:${trip.id}`, 'map'); setSelected(place); consumed = true } } if (consumed) navigate(location.pathname, { replace: true, state: null }) }, [location.pathname, location.state, data.places, navigate, trip.id])
  const addCandidate = async (candidate: PlaceCandidate, details: { startTime: string; notes: string }) => { await addPlace({ tripId: trip.id, day, name: candidate.name, address: candidate.address || '', latitude: candidate.latitude, longitude: candidate.longitude, startTime: details.startTime, notes: details.notes, providerPlaceId: candidate.providerPlaceId, googleMapsUrl: candidate.googleMapsUrl, source: candidate.source }); setAddOpen(false); setDraftPin(null); setPinMode(false) }
  return <section className="map-screen"><div className="map-controls"><div className="day-switcher"><button disabled={day === 0} onClick={() => setDay(day - 1)}><ChevronLeft size={20} /></button><strong>{dayLabel(trip.startDate, day)}</strong><button disabled={day === tripDayCount(trip.startDate, trip.endDate) - 1} onClick={() => setDay(day + 1)}><ChevronRight size={20} /></button></div><div className="view-toggle"><button className={view === 'map' ? 'is-active' : ''} onClick={() => setView('map')}><MapIcon size={15} /> MAP</button><button className={view === 'list' ? 'is-active' : ''} onClick={() => setView('list')}><List size={15} /> LIST</button></div></div>
    {view === 'map' ? <div className="map-stage"><MapCanvas places={places} focusedId={selected?.id} resetKey={day} pinMode={pinMode} draftPin={draftPin} onSelect={setSelected} onMapClick={(coordinate) => setDraftPin(coordinate)} />{pinMode && <div className="pin-mode-banner"><MousePointer2 size={16} /><span>{draftPin ? '이 위치를 저장하거나 다른 곳을 탭하세요' : '지도에서 위치를 탭하세요'}</span><button onClick={() => { setPinMode(false); setDraftPin(null) }}>취소</button></div>}{places.length === 0 && !pinMode && <div className="map-empty"><span>Day {day + 1}에 아직 일정이 없어요</span><button onClick={() => setAddOpen(true)}>첫 장소 추가</button></div>}{draftPin ? <button className="confirm-pin-button" onClick={() => setAddOpen(true)}>이 위치 저장</button> : !pinMode && <button className="map-fab" onClick={() => setAddOpen(true)}><Plus size={24} /></button>}</div> : <div className="list-stage">{places.length === 0 ? <EmptyState icon={MapPin} title={`Day ${day + 1} 일정이 비어 있어요`} description="장소를 추가하면 이동 순서와 교통 정보를 정리할 수 있어요." action={<Button onClick={() => setAddOpen(true)}><Plus size={17} /> 장소 추가</Button>} /> : <ItineraryList places={places} segments={segments} onReorder={(ids) => reorderPlaces(trip.id, day, ids)} onSelect={setSelected} onSegment={(from, to, segment) => setSegmentPair({ from, to, segment })} />}<button className="list-add" onClick={() => setAddOpen(true)}><Plus size={18} /> 장소 추가</button></div>}
    <AddPlaceSheet open={addOpen} initialQuery={(location.state as { placeName?: string } | null)?.placeName || ''} draftPin={draftPin} onClose={() => setAddOpen(false)} onStartPin={() => { setAddOpen(false); setView('map'); setPinMode(true); setDraftPin(null) }} onAdd={addCandidate} />
    <Sheet open={Boolean(selected)} title="장소 정보" onClose={() => setSelected(null)}>{selected && <div className="place-detail"><span className="place-detail__icon"><MapPin size={22} /></span><h3>{selected.name}</h3><p>{selected.address || '주소 없음'}</p>{selected.startTime && <time>{selected.startTime}</time>}{selected.notes && <div className="note-box">{selected.notes}</div>}<a className="button button--secondary button--full" href={selected.googleMapsUrl || googleMapsUrl(selected.name, selected.latitude, selected.longitude)} target="_blank" rel="noreferrer"><Navigation size={17} /> Google Maps에서 열기</a><Button full onClick={() => { void sendMessage(trip.id, selected.name, 'PLACE_SHARE', { referencedPlaceId: selected.id }).catch(() => {}); setSelected(null) }}><Send size={17} /> 채팅에 공유</Button><button className="text-danger" onClick={() => { void deletePlace(selected.id).then(() => setSelected(null)).catch(() => {}) }}><Trash2 size={16} /> 장소 삭제</button></div>}</Sheet>
    <TransportSheet pair={segmentPair} tripId={trip.id} day={day} onClose={() => setSegmentPair(null)} onSave={(segment) => { void upsertSegment(segment).then(() => setSegmentPair(null)).catch(() => {}) }} />
  </section>
}

function AddPlaceSheet({ open, initialQuery, draftPin, onClose, onStartPin, onAdd }: { open: boolean; initialQuery: string; draftPin: Coordinate | null; onClose: () => void; onStartPin: () => void; onAdd: (candidate: PlaceCandidate, details: { startTime: string; notes: string }) => Promise<void> }) {
  const [mode, setMode] = useState<'menu' | 'search' | 'link' | 'confirm'>('menu'); const [queryText, setQueryText] = useState(initialQuery); const [linkText, setLinkText] = useState(''); const [results, setResults] = useState<PlaceSearchResult[]>([]); const [candidate, setCandidate] = useState<PlaceCandidate | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [startTime, setStartTime] = useState(''); const [notes, setNotes] = useState('')
  useEffect(() => { if (!open) return; setQueryText(initialQuery); setLinkText(''); setResults([]); setCandidate(null); setStartTime(''); setNotes(''); setLoading(false); setError(''); if (draftPin) { setCandidate({ name: 'Pinned location', address: `${draftPin.latitude.toFixed(5)}, ${draftPin.longitude.toFixed(5)}`, ...draftPin, source: 'manual_pin' }); setMode('confirm') } else if (initialQuery) setMode('search'); else setMode('menu') }, [open, draftPin, initialQuery])
  const search = async (event: FormEvent) => { event.preventDefault(); if (queryText.trim().length < 2) return; setLoading(true); setError(''); try { const found = await searchPlaces(queryText); setResults(found); if (!found.length) setError('검색 결과가 없어요. 다른 이름이나 지역을 함께 입력해 보세요.') } catch { setError('검색 서비스를 사용할 수 없어요. 링크 붙여넣기나 직접 핀을 이용해 주세요.') } finally { setLoading(false) } }
  const parseLink = async (event: FormEvent) => {
    event.preventDefault(); setLoading(true); setError('')
    try {
      const result = await parseOrResolveGoogleMapsUrl(linkText)
      let place: ParsedGoogleMapsPlace | null = result.ok ? result.place : null
      if (!result.ok && result.reason === 'coordinates_missing' && result.fallbackQuery) {
        const fallback = googleMapsSearchFallbacks(result.fallbackQuery)
        for (const query of fallback.queries) {
          const matches = await searchPlaces(query).catch(() => [])
          const match = matches[0]; if (!match) continue
          place = { latitude: match.latitude, longitude: match.longitude, name: fallback.name || match.name, googleMapsUrl: linkText.trim(), source: 'google_maps' }; break
        }
      }
      if (!place) { const reason = result.ok ? 'coordinates_missing' : result.reason; setError(reason === 'resolver_not_configured' ? 'Google Maps 단축 링크 확인 서버가 아직 설정되지 않았어요.' : reason === 'resolve_failed' || reason === 'short_link' ? 'Google Maps 단축 링크를 펼치지 못했어요. 잠시 후 다시 시도해 주세요.' : reason === 'coordinates_missing' ? 'Google Maps 링크는 확인했지만 위치 좌표를 찾지 못했어요.' : 'Google Maps 링크 형식을 확인해 주세요.'); return }
      let address: string | null = null
      try { address = await reverseGeocode(place.latitude, place.longitude) } catch { /* Coordinates remain usable when Nominatim is unavailable. */ }
      setCandidate({ ...place, address: address || `주소 정보를 가져오지 못했어요 · ${place.latitude.toFixed(5)}, ${place.longitude.toFixed(5)}` }); setMode('confirm')
    } finally { setLoading(false) }
  }
  const title = mode === 'menu' ? '장소 추가' : mode === 'search' ? '장소 검색' : mode === 'link' ? 'Google Maps 링크' : '일정에 추가'
  return <Sheet open={open} title={title} onClose={onClose} tall>{mode === 'menu' && <div className="add-place-menu"><button onClick={() => setMode('search')}><span><Search size={20} /></span><div><strong>장소 검색</strong><small>OpenStreetMap에서 이름으로 찾기</small></div><ChevronRight size={18} /></button><button onClick={() => setMode('link')}><span><LinkIcon size={20} /></span><div><strong>Google Maps 링크 붙여넣기</strong><small>링크 좌표로 T Log 지도에 핀 만들기</small></div><ChevronRight size={18} /></button><button onClick={onStartPin}><span><MousePointer2 size={20} /></span><div><strong>지도에 직접 핀</strong><small>원하는 위치를 지도에서 탭하기</small></div><ChevronRight size={18} /></button></div>}
    {mode === 'search' && <><form className="explicit-search" onSubmit={search}><label className="search-field"><Search size={19} /><input autoFocus value={queryText} onChange={(event) => setQueryText(event.target.value)} placeholder="장소 이름과 도시" /></label><Button type="submit" loading={loading}>검색</Button></form><div className="search-results">{results.map((result) => <button key={result.id} onClick={() => { setCandidate({ ...result, providerPlaceId: result.id }); setMode('confirm') }}><span><MapPin size={18} /></span><div><strong>{result.name}</strong><small>{result.address}</small></div><ChevronRight size={18} /></button>)}{error && <p className="inline-error">{error}</p>}<button className="back-method" onClick={() => setMode('menu')}><ChevronLeft size={16} /> 다른 방법 선택</button></div></>}
    {mode === 'link' && <form className="sheet-form" onSubmit={parseLink}><div className="link-help"><LinkIcon size={18} /><p>Google Maps 링크에서 좌표만 읽어 T Log 자체 지도에 핀을 만들어요. Google 지도를 가져오거나 삽입하지 않습니다.</p></div><label className="field"><span>Google Maps URL</span><textarea required value={linkText} onChange={(event) => { setLinkText(event.target.value); setError('') }} placeholder="https://maps.app.goo.gl/..." /></label>{error && <p className="form-error">{error}</p>}<Button full type="submit" loading={loading}>위치 확인</Button><Button full type="button" variant="ghost" onClick={() => setMode('menu')}>다른 방법 선택</Button></form>}
    {mode === 'confirm' && candidate && <form className="sheet-form" onSubmit={async (event) => { event.preventDefault(); setLoading(true); setError(''); try { await onAdd(candidate, { startTime, notes }); setCandidate(null); setMode('menu') } catch { setError('장소를 Firebase에 저장하지 못했어요. 다시 시도해 주세요.') } finally { setLoading(false) } }}><div className="selected-place"><MapPin size={20} /><div><strong>{candidate.name}</strong><span>{candidate.address || `${candidate.latitude.toFixed(5)}, ${candidate.longitude.toFixed(5)}`}</span></div></div><label className="field"><span>장소 이름</span><input required value={candidate.name} onChange={(event) => setCandidate({ ...candidate, name: event.target.value })} /></label><label className="field"><span>주소</span><input readOnly value={candidate.address || `${candidate.latitude.toFixed(5)}, ${candidate.longitude.toFixed(5)}`} /></label><label className="field"><span>시작 시간 · 선택</span><input type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} /></label><label className="field"><span>메모 · 선택</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="예약, 티켓, 만날 장소..." /></label>{error && <p className="form-error">{error}</p>}<Button full type="submit" loading={loading}>추가</Button><Button full type="button" variant="ghost" onClick={() => { setCandidate(null); setMode('menu') }}>다른 방법 선택</Button></form>}</Sheet>
}

function TransportSheet({ pair, tripId, day, onClose, onSave }: { pair: { from: ItineraryPlace; to: ItineraryPlace; segment?: TransportSegment } | null; tripId: string; day: number; onClose: () => void; onSave: (segment: TransportSegment) => void }) {
  const [mode, setMode] = useState<TransportMode>('walk'); const [duration, setDuration] = useState(''); const [distance, setDistance] = useState(''); const [notes, setNotes] = useState('')
  useEffect(() => { if (pair) { setMode(pair.segment?.mode || 'walk'); setDuration(pair.segment?.duration?.toString() || ''); setDistance(pair.segment?.distance?.toString() || ''); setNotes(pair.segment?.notes || '') } }, [pair])
  if (!pair) return null
  const modes: Array<[TransportMode, string]> = [['walk', '도보'], ['driving', '자동차'], ['transit', '대중교통'], ['cycling', '자전거'], ['ferry', '페리'], ['shuttle', '셔틀'], ['other', '기타']]
  return <Sheet open title="이동 정보" onClose={onClose}><form className="sheet-form" onSubmit={(event: FormEvent) => { event.preventDefault(); onSave({ id: pair.segment?.id || uid(), tripId, day, sourcePlaceId: pair.from.id, destinationPlaceId: pair.to.id, mode, duration: duration ? Number(duration) : undefined, distance: distance ? Number(distance) : undefined, notes }) }}><div className="route-summary"><span>{pair.from.name}</span><ExternalLink size={15} /><span>{pair.to.name}</span></div><div className="mode-picker">{modes.map(([value, label]) => <button type="button" className={mode === value ? 'is-active' : ''} key={value} onClick={() => setMode(value)}>{label}</button>)}</div><div className="field-grid"><label className="field"><span>소요 시간 · 분</span><input inputMode="numeric" value={duration} onChange={(event) => setDuration(event.target.value)} /></label><label className="field"><span>거리 · km</span><input inputMode="decimal" value={distance} onChange={(event) => setDistance(event.target.value)} /></label></div><label className="field"><span>메모</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><Button full type="submit">저장</Button></form></Sheet>
}
